"Are you transgender?",
"Are you gay/lesbian/bi/etc.?",
"Are you an adult?",
"Do you know C++ well?",
"Are you currently in a relationship?",
"Are you a part of the staff?",
"Are you currently in school?",
"Do you have your own Discord server? (doesn't include ""test servers"")",
"Do you have a GitHub account?",
"Do you live in the U.S.A.?",
"Do you routinely exercise?",
"Have you ever had a pet?",
"Do you regularly use Rust?",
"Do you often try to program in esoteric programming languages?",
"Are you a part of the GEORGE webring?",
"Do you have more than 10 GitHub repositories?",
"Tabs (Y) or spaces (N)?",
"Is programming your primary hobby?",
"Do people call you by your nickname/real name more often than your username/online name?",
"`if(...)` (Y) or `if (...)` (N)?",
"Do you actively participate in the Esolangs community? (ie. develop and utilize esolangs)",
"Do you enjoy linguistics? (eg. conlangs)",
"Do you use Windows primarily?",
"Would you consider yourself a ""computer whiz""?",
"Are you content with your current living situation?",
"Do you primarily use Python? (ie. use it more often than other languages)",
"Are you a ""long-standing"" member of Esolangs?",
"Do you have a (meaningful) website?",
"Are you currently in high school?",
"Have you ever participated in code guessing?",
"Have you ever had a LyricLy or gollark name derivative?",
"Are you from Europe?",
"Have you ever developed for an embedded system?",
"Are you multilingual?",
"Is English your primary language?"
